version: "3.7"

volumes:
  api-db:

networks:
  api:
    external: true

services:
  api-app:
    build:
      context: ./docker
    volumes:
      - .:/app/:rw
      - ~/.ssh:/home/test0/.ssh:ro
    working_dir: /app
    networks:
      - api

  api-nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - api

  api-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: origin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8088:3306"
    volumes:
      - api-db:/var/lib/mysql/
    networks:
      - api